title: Travels of Mandonkey
author: Richard Mendonca
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Travel stories from my trips to Asia, Africa, Australia and South America.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
